apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-mcp
  template:
    metadata:
      labels:
        app: multi-mcp
    spec:
      containers:
      - name: multi-mcp
        image: multi-mcp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: multi-mcp-service
spec:
  type: NodePort
  selector:
    app: multi-mcp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080